# Generated by Django 2.2.5 on 2020-05-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_deliveryadress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryadress',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.DeliveryAdress'),
        ),
    ]
