# Generated by Django 2.2.5 on 2020-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='us',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
    ]
