# Generated by Django 2.2.5 on 2020-04-06 08:17

from django.db import migrations, models
import toraxnet.accounts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='us',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'Cet numero existe deja'}, max_length=20, unique=True, validators=[toraxnet.accounts.utils.UsernameValidator()]),
        ),
    ]
